% PHASE0_PROCESS_USER_PROTOCOL: tutorial_omega-derived pipeline on the user's
% omega-tutorial-cortical-flow protocol (SpikeData-2, DEV brainstorm).
% Deviation from tutorial_omega: inverse = UNCONSTRAINED MNE kernel
% (minnorm/amplitude/free), NOT fixed-orientation dSPM.
% Every stage asserts non-empty outputs (a prior OMEGA batch silently lost
% the inverse stage) and the Brainstorm report is saved at the end.
BidsDir      = '/Volumes/SpikeData-2/workspace/library/datasets/omega-tutorial';
ProtocolName = 'omega-tutorial-cortical-flow';
NewSubjects  = 'sub-0003, sub-0004, sub-0006, sub-0007, sub-emptyroom';

iProtocol = bst_get('Protocol', ProtocolName);
assert(~isempty(iProtocol), 'Protocol %s not registered in this Brainstorm database', ProtocolName);
gui_brainstorm('SetCurrentProtocol', iProtocol);
db_reload_database(iProtocol);
bst_report('Start');
chk = @(s, what) assert(~isempty(s), 'Stage returned no files: %s', what);

% ===== IMPORT REMAINING SUBJECTS (sub-0002 already imported) =====
bst_process('CallProcess', 'process_import_bids', [], [], ...
    'bidsdir',      {BidsDir, 'BIDS'}, ...
    'selectsubj',   NewSubjects, ...
    'channelalign', 0);

% ===== ALL RAW LINKS (incl. the pre-existing sub-0002 one) =====
sFilesRaw = bst_process('CallProcess', 'process_select_files_data', [], [], ...
    'subjectname', 'All');
chk(sFilesRaw, 'select all raw links');
fprintf('PIPELINE> %d raw links selected\n', numel(sFilesRaw));

% ===== REGISTRATION (tutorial steps) =====
sFilesRaw = bst_process('CallProcess', 'process_headpoints_remove', sFilesRaw, [], 'zlimit', 0);
sFilesRaw = bst_process('CallProcess', 'process_headpoints_refine', sFilesRaw, []);
chk(sFilesRaw, 'headpoints refine');

% ===== CTF CONTINUOUS =====
sFilesRaw = bst_process('CallProcess', 'process_ctf_convert', sFilesRaw, [], 'rectype', 2);
chk(sFilesRaw, 'ctf continuous');

% ===== FILTERING =====
sFilesNotch = bst_process('CallProcess', 'process_notch', sFilesRaw, [], ...
    'freqlist', [60, 120, 180, 240, 300], 'sensortypes', 'MEG, EEG', 'read_all', 1);
chk(sFilesNotch, 'notch');
sFilesBand = bst_process('CallProcess', 'process_bandpass', sFilesNotch, [], ...
    'sensortypes', 'MEG, EEG', 'highpass', 0.3, 'lowpass', 0, ...
    'attenuation', 'strict', 'mirror', 0, 'useold', 0, 'read_all', 1);
chk(sFilesBand, 'bandpass');

% ===== PSD QC =====
sFilesPsd = bst_process('CallProcess', 'process_psd', sFilesBand, [], ...
    'timewindow', [0 100], 'win_length', 4, 'win_overlap', 50, ...
    'sensortypes', 'MEG, EEG', ...
    'edit', struct('Comment','Power', 'TimeBands',[], 'Freqs',[], ...
                   'ClusterFuncTime','none', 'Measure','power', 'Output','all', 'SaveKernel',0));
bst_process('CallProcess', 'process_snapshot', sFilesPsd, [], 'target', 10, 'modality', 1);

% ===== DELETE INTERMEDIATE RAW FOLDERS (tutorial housekeeping) =====
bst_process('CallProcess', 'process_delete', [sFilesRaw, sFilesNotch], [], 'target', 2);

% ===== ARTIFACT CLEANING (rest runs) =====
sFilesBand = bst_process('CallProcess', 'process_select_files_data', [], [], 'subjectname', 'All');
sFilesRest = bst_process('CallProcess', 'process_select_tag', sFilesBand, [], ...
    'tag', 'task-rest', 'search', 1, 'select', 1);
chk(sFilesRest, 'select task-rest');
fprintf('PIPELINE> %d rest runs\n', numel(sFilesRest));
bst_process('CallProcess', 'process_evt_detect_ecg', sFilesRest, [], ...
    'channelname', 'ECG', 'timewindow', [], 'eventname', 'cardiac');
bst_process('CallProcess', 'process_ssp_ecg', sFilesRest, [], ...
    'eventname', 'cardiac', 'sensortypes', 'MEG', 'usessp', 1, 'select', 1);
bst_process('CallProcess', 'process_snapshot', sFilesRest, [], 'target', 1, 'modality', 1, 'orient', 1);
bst_process('CallProcess', 'process_snapshot', sFilesRest, [], 'target', 2, 'modality', 1);

% ===== NOISE COVARIANCE (noise recordings -> copy everywhere) =====
sFilesNoise = bst_process('CallProcess', 'process_select_tag', sFilesBand, [], ...
    'tag', 'task-noise', 'search', 1, 'select', 1);
chk(sFilesNoise, 'select task-noise');
fprintf('PIPELINE> %d noise runs\n', numel(sFilesNoise));
bst_process('CallProcess', 'process_noisecov', sFilesNoise, [], ...
    'baseline', [], 'sensortypes', 'MEG', 'target', 1, 'dcoffset', 1, ...
    'identity', 0, 'copycond', 1, 'copysubj', 1, 'copymatch', 1, 'replacefile', 1);

% ===== HEAD MODEL (rest runs) =====
bst_process('CallProcess', 'process_headmodel', sFilesRest, [], ...
    'sourcespace', 1, 'meg', 3);   % cortex surface, overlapping spheres

% ===== UNCONSTRAINED MNE KERNEL (deviation from tutorial dSPM) =====
sSrcRest = bst_process('CallProcess', 'process_inverse_2018', sFilesRest, [], ...
    'output',  2, ...              % kernel only: one per file
    'inverse', struct(...
         'Comment',        'MNE: MEG (Unconstr.)', ...
         'InverseMethod',  'minnorm', ...
         'InverseMeasure', 'amplitude', ...
         'SourceOrient',   {{'free'}}, ...
         'Loose',          0.2, ...
         'UseDepth',       1, ...
         'WeightExp',      0.5, ...
         'WeightLimit',    10, ...
         'NoiseMethod',    'reg', ...
         'NoiseReg',       0.1, ...
         'SnrMethod',      'fixed', ...
         'SnrRms',         1e-06, ...
         'SnrFixed',       3, ...
         'ComputeKernel',  1, ...
         'DataTypes',      {{'MEG'}}));
chk(sSrcRest, 'unconstrained MNE kernels (KNOWN prior failure mode: empty return)');
fprintf('PIPELINE> %d unconstrained MNE kernels computed\n', numel(sSrcRest));

% ===== SAVE REPORT + SUMMARY =====
db_save(1);
ReportFile = bst_report('Save', []);
fprintf('PIPELINE REPORT: %s\n', ReportFile);
fprintf('OMEGA PIPELINE PASSED: %d rest runs cleaned, %d noise runs, %d kernels\n', ...
    numel(sFilesRest), numel(sFilesNoise), numel(sSrcRest));
