function preventad_import(BidsDir, SubjectNames, DoSnapshots)
% PREVENTAD_IMPORT: Import + preprocess + source-map the PREVENT-AD BIDS MEG dataset.
%
% Adapted from toolbox/script/tutorial_omega.m (Resting state / OMEGA tutorial),
% with two project-specific customizations:
%   1. Anatomy is downsampled with the FreeSurfer ICOSPHERE method at ICO5
%      (20484 vertices total) - HARD REQUIREMENT for the differential/spectral
%      analysis engine (reducepatch breaks the sphere-registered correspondence).
%   2. In addition to the standard dSPM inverse, a DIRAC dSPM inverse is computed
%      on the SAME unconstrained overlapping-spheres head model (the Dirac-basis
%      projection is performed internally by process_inverse_dirac).
%
% Imports into the EXISTING 'preventad' protocol (does NOT delete/recreate it),
% so per-subject and incremental batch runs are safe.
%
% USAGE:  preventad_import()                          % all subjects, default BidsDir
%         preventad_import(BidsDir)                   % all subjects
%         preventad_import(BidsDir, 'sub-MTL0002')    % single subject (TEST)
%         preventad_import(BidsDir, {'sub-MTL0002','sub-MTL0005'})  % subset
%
% INPUTS:
%     BidsDir      : Full path to the PREVENT-AD BIDS MEG root.
%                    Default: /Volumes/SpikeData-2/workspace/library/datasets/preventad/meg
%     SubjectNames : Comma-separated string or cell array of BIDS subject names
%                    to import (empty = all subjects).
%     DoSnapshots  : (default true) generate the QC figure snapshots (spectrum,
%                    registration, SSP, power contact-sheet). Set FALSE for headless
%                    batch runs: the 3D figure rendering can hang nondeterministically
%                    in `matlab -batch`, and the snapshots are cosmetic (no data impact).
%
% Author: Diellor Basha, 2026 (template: Francois Tadel, tutorial_omega)


%% ===== PARSE INPUTS =====
if (nargin < 1) || isempty(BidsDir)
    BidsDir = '/Volumes/SpikeData-2/workspace/library/datasets/preventad/meg';
end
if ~file_exist(BidsDir)
    error('BIDS directory not found: %s', BidsDir);
end
if (nargin < 2) || isempty(SubjectNames)
    SelectSubj = '';                                 % empty = all subjects
elseif iscell(SubjectNames)
    SelectSubj = strjoin(SubjectNames, ', ');
else
    SelectSubj = SubjectNames;                       % already a (comma-sep) string
end
if (nargin < 3) || isempty(DoSnapshots)
    DoSnapshots = true;                              % default: generate QC snapshots
end


%% ===== SELECT EXISTING PROTOCOL =====
% The 'preventad' protocol must already exist (created by the user in the GUI).
ProtocolName = 'preventad';
if ~brainstorm('status')
    brainstorm nogui
end
iProtocol = bst_get('Protocol', ProtocolName);
if isempty(iProtocol)
    error(['Unknown protocol: ' ProtocolName 10 ...
           'Create the "preventad" protocol in Brainstorm before running this script.']);
end
if (iProtocol ~= bst_get('iProtocol'))
    gui_brainstorm('SetCurrentProtocol', iProtocol);
end
% Start a new report
bst_report('Start');


%% ===== IMPORT BIDS DATASET =====
% Process: Import BIDS dataset  (ICO5 icosphere anatomy = HARD REQUIREMENT)
sFilesRaw = bst_process('CallProcess', 'process_import_bids', [], [], ...
    'bidsdir',          {BidsDir, 'BIDS'}, ...
    'selectsubj',       SelectSubj, ...
    'downsamplemethod', 'icosphere', ...   % FreeSurfer sphere-registered resampling
    'icolevel',         'ico5', ...        % 20484 vertices total (10242/hemi)
    'nvertices',        15000, ...         % ignored on the icosphere path
    'channelalign',     0);
if isempty(sFilesRaw)
    error('BIDS import produced no files. Check BidsDir / SubjectNames.');
end

% Process: Remove head points
sFilesRaw = bst_process('CallProcess', 'process_headpoints_remove', sFilesRaw, [], ...
    'zlimit', 0);

% Process: Refine registration
sFilesRaw = bst_process('CallProcess', 'process_headpoints_refine', sFilesRaw, []);

% Process: Convert to continuous (CTF): Continuous
sFilesRaw = bst_process('CallProcess', 'process_ctf_convert', sFilesRaw, [], ...
    'rectype', 2);  % Continuous

% Process: Resample 2400 -> 1200 Hz. Done FIRST so all subsequent filtering runs
% on half the samples and the surviving continuous file is half-size. New Nyquist
% (600 Hz) keeps every notched line-noise harmonic (60-300 Hz) and the full
% analysis band (<=90 Hz), so it is lossless for this analysis.
sFilesResample = bst_process('CallProcess', 'process_resample', sFilesRaw, [], ...
    'freq', 1200);


%% ===== PRE-PROCESSING =====
% Process: Notch filter: 60Hz 120Hz 180Hz 240Hz 300Hz
sFilesNotch = bst_process('CallProcess', 'process_notch', sFilesResample, [], ...
    'freqlist',    [60, 120, 180, 240, 300], ...
    'sensortypes', 'MEG, EEG', ...
    'read_all',    1);

% Process: High-pass:0.3Hz
sFilesBand = bst_process('CallProcess', 'process_bandpass', sFilesNotch, [], ...
    'sensortypes', 'MEG, EEG', ...
    'highpass',    0.3, ...
    'lowpass',     0, ...
    'attenuation', 'strict', ...  % 60dB
    'mirror',      0, ...
    'useold',      0, ...
    'read_all',    1);

% Process: Power spectrum density (Welch)
sFilesPsdAfter = bst_process('CallProcess', 'process_psd', sFilesBand, [], ...
    'timewindow',  [0 100], ...
    'win_length',  4, ...
    'win_overlap', 50, ...
    'sensortypes', 'MEG, EEG', ...
    'edit',        struct(...
         'Comment',         'Power', ...
         'TimeBands',       [], ...
         'Freqs',           [], ...
         'ClusterFuncTime', 'none', ...
         'Measure',         'power', ...
         'Output',          'all', ...
         'SaveKernel',      0));

% Process: Snapshot: Frequency spectrum
if DoSnapshots
bst_process('CallProcess', 'process_snapshot', sFilesPsdAfter, [], ...
    'target',         10, ...  % Frequency spectrum
    'modality',       1);      % MEG (All)
end

% Process: Delete intermediate folders (raw + resample + notch); keep only the
% final band-pass output (resampled, notched, high-passed continuous)
bst_process('CallProcess', 'process_delete', [sFilesRaw, sFilesResample, sFilesNotch], [], ...
    'target', 2);  % Delete folders


%% ===== ARTIFACT CLEANING =====
% Operate on the band-pass output of THIS run (scoped to the imported subjects),
% not a protocol-wide 'All' selection - keeps per-subject / batch runs safe.
% Process: Select file names with tag: task-rest
sFilesRest = bst_process('CallProcess', 'process_select_tag', sFilesBand, [], ...
    'tag',    'task-rest', ...
    'search', 1, ...  % Search the file names
    'select', 1);     % Select only the files with the tag

% Process: Detect heartbeats (ECG -> 'cardiac' events)
bst_process('CallProcess', 'process_evt_detect_ecg', sFilesRest, [], ...
    'channelname', 'ECG', ...
    'timewindow',  [], ...
    'eventname',   'cardiac');

% Process: Detect eye blinks (VEOG -> 'blink' events)
bst_process('CallProcess', 'process_evt_detect_eog', sFilesRest, [], ...
    'channelname', 'VEOG', ...
    'timewindow',  [], ...
    'eventname',   'blink');

% Process: Detect saccades / horizontal eye movements (HEOG -> 'saccade' events)
bst_process('CallProcess', 'process_evt_detect_eog', sFilesRest, [], ...
    'channelname', 'HEOG', ...
    'timewindow',  [], ...
    'eventname',   'saccade');

% Process: Remove cardiac events that coincide with blinks (+/-0.25s) so the
% cardiac SSP projector is not contaminated by blink artifacts.
bst_process('CallProcess', 'process_evt_remove_simult', sFilesRest, [], ...
    'remove', 'cardiac', ...
    'target', 'blink', ...
    'dt',     0.25, ...
    'rename', 0);

% Process: SSP ECG: cardiac
bst_process('CallProcess', 'process_ssp_ecg', sFilesRest, [], ...
    'eventname',   'cardiac', ...
    'sensortypes', 'MEG', ...
    'usessp',      1, ...
    'select',      1);

% Process: SSP EOG: blink (vertical eye movements)
bst_process('CallProcess', 'process_ssp_eog', sFilesRest, [], ...
    'eventname',   'blink', ...
    'sensortypes', 'MEG', ...
    'usessp',      1, ...
    'select',      1);

% Process: SSP EOG: saccade (horizontal eye movements)
bst_process('CallProcess', 'process_ssp_eog', sFilesRest, [], ...
    'eventname',   'saccade', ...
    'sensortypes', 'MEG', ...
    'usessp',      1, ...
    'select',      1);

%% ===== AUTOMATIC BAD-SEGMENT DETECTION =====
% Process: Detect other artifacts - frequency-band power outliers (sensitivity 3):
%   1-7 Hz   = eye/subject movement, dental work
%   40-240 Hz = muscle noise, sensor/SQUID artifacts
bst_process('CallProcess', 'process_evt_detect_badsegment', sFilesRest, [], ...
    'timewindow',  [], ...
    'sensortypes', 'MEG', ...
    'threshold',   3, ...   % sensitivity (1=least .. 5=most)
    'isLowFreq',   1, ...
    'isHighFreq',  1);

% Mark detected segments BAD so they are excluded from PSD / source analysis.
% Brainstorm treats events whose label contains 'bad' as bad segments; the
% detector names them '1-7Hz' / '40-240Hz', so rename with a 'bad_' prefix.
bst_process('CallProcess', 'process_evt_rename', sFilesRest, [], ...
    'src',  '1-7Hz, 40-240Hz', ...
    'dest', 'bad_1-7Hz, bad_40-240Hz');

% Process: Snapshot: Sensors/MRI registration + SSP projectors
if DoSnapshots
bst_process('CallProcess', 'process_snapshot', sFilesRest, [], ...
    'target',         1, ...  % Sensors/MRI registration
    'modality',       1, ...  % MEG (All)
    'orient',         1);     % left

% Process: Snapshot: SSP projectors
bst_process('CallProcess', 'process_snapshot', sFilesRest, [], ...
    'target',         2, ...  % SSP projectors
    'modality',       1);     % MEG (All)
end


%% ===== SOURCE ESTIMATION =====
% Process: Select file names with tag: task-noise (empty-room)
sFilesNoise = bst_process('CallProcess', 'process_select_tag', sFilesBand, [], ...
    'tag',    'task-noise', ...
    'search', 1, ...  % Search the file names
    'select', 1);     % Select only the files with the tag

% Process: Compute covariance (noise) - copied to the subject's other conditions
bst_process('CallProcess', 'process_noisecov', sFilesNoise, [], ...
    'baseline',       [], ...
    'sensortypes',    'MEG', ...
    'target',         1, ...  % Noise covariance
    'dcoffset',       1, ...  % Block by block
    'identity',       0, ...
    'copycond',       1, ...
    'copysubj',       1, ...
    'copymatch',      1, ...
    'replacefile',    1);     % Replace

% Process: Compute head model - ONE overlapping-spheres model feeds BOTH inverses
bst_process('CallProcess', 'process_headmodel', sFilesRest, [], ...
    'sourcespace', 1, ...  % Cortex surface
    'meg',         3);     % Overlapping spheres

% Process: Compute manifold (nxr geometry backbone) on each subject's cortex.
% Done BEFORE the Dirac inverse so the manifold_ node is available for later
% differential/spectral analysis. Idempotent (find-or-create), gauge=trivial.
bst_process('CallProcess', 'process_tess_manifold', sFilesRest, [], ...
    'gauge',          'trivial', ...
    'forcerecompute', 0);

% Process: Compute sources [2018] - STANDARD dSPM, UNCONSTRAINED orientation
% (free 3-component sources; Brainstorm tags the comment "(Unconstr)").
sSrcRest = bst_process('CallProcess', 'process_inverse_2018', sFilesRest, [], ...
    'output',  2, ...  % Kernel only: one per file
    'inverse', struct(...
         'Comment',        'dSPM: MEG', ...
         'InverseMethod',  'minnorm', ...
         'InverseMeasure', 'dspm2018', ...
         'SourceOrient',   {{'free'}}, ...
         'Loose',          0.2, ...
         'UseDepth',       1, ...
         'WeightExp',      0.5, ...
         'WeightLimit',    10, ...
         'NoiseMethod',    'reg', ...
         'NoiseReg',       0.1, ...
         'SnrMethod',      'fixed', ...
         'SnrRms',         1e-06, ...
         'SnrFixed',       3, ...
         'ComputeKernel',  1, ...
         'DataTypes',      {{'MEG'}}));

% Process: Compute sources - DIRAC dSPM (unconstrained Dirac eigenbasis).
% Uses the SAME overlapping-spheres head model; the Dirac-basis projection +
% reconstruction are internal. Process defaults: 400 modes/hemi, tau=0.5,
% SNR=3, noisereg=0.1, measure=dspm2018.
sSrcRestDirac = bst_process('CallProcess', 'process_inverse_dirac', sFilesRest, [], ...
    'measure',     'dspm2018', ...
    'snr',         3, ...
    'nmodes',      400, ...
    'tau',         0.5, ...
    'noisereg',    0.1, ...
    'sensortypes', 'MEG');


%% ===== POWER MAPS (standard dSPM only) =====
% Process: Power spectrum density (Welch)
sSrcPsd = bst_process('CallProcess', 'process_psd', sSrcRest, [], ...
    'timewindow',  [0, 100], ...
    'win_length',  4, ...
    'win_overlap', 50, ...
    'clusters',    {}, ...
    'scoutfunc',   1, ...  % Mean
    'edit',        struct(...
         'Comment',         'Power,FreqBands', ...
         'TimeBands',       [], ...
         'Freqs',           {{'delta', '2, 4', 'mean'; 'theta', '5, 7', 'mean'; 'alpha', '8, 12', 'mean'; 'beta', '15, 29', 'mean'; 'gamma1', '30, 59', 'mean'; 'gamma2', '60, 90', 'mean'}}, ...
         'ClusterFuncTime', 'none', ...
         'Measure',         'power', ...
         'Output',          'all', ...
         'SaveKernel',      0));

% Process: Spectrum normalization (relative power)
sSrcPsdNorm = bst_process('CallProcess', 'process_tf_norm', sSrcPsd, [], ...
    'normalize', 'relative', ...
    'overwrite', 0);

% Process: Project on default anatomy: surface
sSrcPsdProj = bst_process('CallProcess', 'process_project_sources', sSrcPsdNorm, [], ...
    'headmodeltype', 'surface');  % Cortex surface

% Process: Spatial smoothing (3.00)
sSrcPsdProj = bst_process('CallProcess', 'process_ssmooth_surfstat', sSrcPsdProj, [], ...
    'fwhm',      3, ...
    'overwrite', 1);

% Process: Average: Everything
sSrcPsdAvg = bst_process('CallProcess', 'process_average', sSrcPsdProj, [], ...
    'avgtype',   1, ...  % Everything
    'avg_func',  1, ...  % Arithmetic average:  mean(x)
    'weighted',  0, ...
    'matchrows', 0, ...
    'iszerobad', 0);

% Screen capture of final result (skipped in headless batch: the 3D contact-sheet
% render can hang nondeterministically under `matlab -batch`; this is the step that
% wedged sub-MTL0032. Data are fully saved above regardless.)
if DoSnapshots && ~isempty(sSrcPsdAvg)
    hFig = view_surface_data([], sSrcPsdAvg.FileName);
    set(hFig, 'Position', [200 200 200 200]);
    hFigContact = view_contactsheet(hFig, 'freq', 'fig');
    bst_report('Snapshot', hFigContact, sSrcPsdAvg.FileName, 'Power');
    close([hFig, hFigContact]);
end


%% ===== REPORT =====
ReportFile = bst_report('Save', []);
% bst_report('Open') renders HTML via a JDK class (sun.misc.BASE64Encoder) that
% is absent on Apple-silicon/newer-JVM setups; never let report display abort a
% (possibly batch) run - the report file itself is already saved above.
try
    bst_report('Open', ReportFile);
catch
    fprintf('Report saved (display skipped): %s\n', ReportFile);
end

disp('===== preventad_import: DONE =====');
